Cleanup and improve

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -55,3 +55,14 @@ jobs:
     - name: Build
       # Build your program with the given configuration
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+
+    - name: Test
+      run: |
+         cd ${{github.workspace}}/My Projects/Torque3D/game
+         ./Torque3D runTests.tscript
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+         report_paths: '${{github.workspace}}/My Projects/Torque3D/game/TEST-*.xml'
